# Generated by Django 3.1 on 2020-09-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRSTNAME', models.CharField(max_length=50)),
                ('LASTNAME', models.CharField(max_length=50)),
                ('CLGNAME', models.CharField(max_length=50)),
                ('BRANCH', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('GENDER', models.CharField(max_length=50)),
                ('DEPT', models.CharField(max_length=50)),
                ('STUDENT_ID', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Student_Info',
                'verbose_name_plural': 'Student_Infos',
            },
        ),
    ]
