# Generated by Django 3.2.5 on 2021-07-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('semail', models.EmailField(max_length=100)),
                ('spass', models.CharField(max_length=100)),
                ('comment', models.CharField(default='Not available', max_length=100)),
            ],
        ),
    ]
