# Generated by Django 3.2.5 on 2021-07-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirTicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(default=None, max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('city_name', models.CharField(max_length=30)),
                ('ticket_no', models.IntegerField()),
                ('no_of_tickets', models.IntegerField()),
                ('seat_no', models.IntegerField()),
            ],
        ),
    ]
