# Generated by Django 3.2.5 on 2021-07-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airticketmodel',
            old_name='city_name',
            new_name='From',
        ),
        migrations.AddField(
            model_name='airticketmodel',
            name='To',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
