# Generated by Django 3.2.5 on 2021-07-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_auto_20210729_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airticketmodel',
            name='seat_no',
        ),
    ]
