# Generated by Django 3.0 on 2021-08-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_remove_airticketmodel_seat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airticketmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
